main: user.liltinyten.pluginrequest.worldwhitelist.Main
name: WorldWhitelist
version: 1.15
author: liltinyten
description: Allows you to whitelist worlds!
commands:
    wwhitelist:
        description: Whitelist Worlds!