main: user.liltinyten.pluginrequest.worldwhitelist.Main
name: WorldWhitelist
version: 1.14
api-version: 1.16
author: liltinyten
description: Allows you to whitelist worlds!
commands:
    wwhitelist:
        description: Whitelist Worlds!